dt                          0.001   # in seconds
contact_force_threshold     0.1     # in Newton

base_frame                  l_sole
left_contact_frame          l_sole
right_contact_frame         r_sole
close_loop_with_zmp         false

com_trajectory_type         sinusoidal  # ("spline" or "sinusoidal")

[SPLINE_COM_TRAJECTORY]
# com_knots_delta_x        (0.0, 0.0,  0.0,  0.03,  0.03, -0.005, -0.005, 0.0,  0.0, 0.0)    # in meter
# com_knots_delta_y        (0.0, 0.0, 0.04, 0.04, -0.04, -0.04,  0.04, 0.04, 0.0, 0.0)    # in meter
# com_knots_delta_z        (0.0, -0.01, -0.01,  -0.01,   -0.01,   -0.01,   -0.01,  -0.01,  -0.01, 0.0)    # in meter


com_knots_delta_x        (0.0, 0.0,  0.0,  0.0,  0.0, 0.0, 0.0, 0.0,  0.0, 0.0, 0.0)    # in meter
com_knots_delta_y        (0.0, 0.0, 0.00, 0.00, -0.00, -0.00,  0.00, 0.00, 0.0, 0.0, 0.0)    # in meter
com_knots_delta_z        (0.0, -0.01, -0.06,  -0.01,   -0.06,   -0.01,   -0.06,  -0.01,  -0.06, -0.01, 0.0)    # in meter

motion_duration          0.2   # in seconds (set to 0.5 for slower trajectory)
motion_timeout           1.0   # in seconds


### Funziona con il walking
# com_knots_delta_x        (0.0, 0.0,  0.0,  0.0,  0.0, 0.0, 0.0, 0.0,  0.0, 0.0, 0.0)    # in meter
# com_knots_delta_y        (0.0, 0.0, 0.00, 0.00, -0.00, -0.00,  0.00, 0.00, 0.0, 0.0, 0.0)    # in meter
# com_knots_delta_z        (0.0, -0.01, -0.02,  -0.01,   -0.02,   -0.01,   -0.02,  -0.01,  -0.02, -0.01, 0.0)    # in meter

# motion_duration          0.2   # in seconds
# motion_timeout           0.1   # in seconds


### Su e giu tanto 
# com_knots_delta_x        (0.0, 0.03,  0.03,  0.03,  0.03, 0.03, 0.03, 0.03,  0.03, 0.0)    # in meter
# com_knots_delta_y        (0.0, 0.0, 0.00, 0.00, -0.00, -0.00,  0.00, 0.00, 0.0, 0.0)    # in meter
# com_knots_delta_z        (0.0, -0.01, -0.04,  -0.06,   -0.08,   -0.10,   -0.07,  -0.05,  -0.03, 0.0)    # in meter

# motion_duration          0.5   # in seconds
# motion_timeout           1.0   # in seconds


#### Su e giu due gambe
# com_knots_delta_x        (0.0, 0.03,  0.03,  0.03,  0.03, 0.03, 0.03, 0.03,  0.03, 0.0)    # in meter
# com_knots_delta_y        (0.0, 0.0, 0.00, 0.00, -0.00, -0.00,  0.00, 0.00, 0.0, 0.0)    # in meter
# com_knots_delta_z        (0.0, -0.01, -0.03,  -0.05,   -0.0,   -0.02,   -0.0,  -0.04,  -0.02, 0.0)    # in meter

# motion_duration          0.75   # in seconds
# motion_timeout           1.0   # in seconds

[SINUSOIDAL_COM_TRAJECTORY]
t_start                             0.0   # in seconds
t_end                              20.0   # in seconds
com_amplitude_x                     0.0   # in meter
com_amplitude_y                     -0.00   # in meter
com_amplitude_z                     0.00   # in meter
com_frequency_x                     0.0   # in Hz
com_frequency_y                     0.0   # in Hz
com_frequency_z                     0.0   # in Hz

[COM_ZMP_CONTROLLER]
com_gain                        (5.0, 5.0)
zmp_gain                        (1.0, 1.0)

[include IK "./blf_balancing_position_control/ik.ini"]
[include ROBOT_CONTROL "./blf_balancing_position_control/robot_control.ini"]
[include SENSOR_BRIDGE "./blf_balancing_position_control/sensor_bridge.ini"]
[include CONTACT_WRENCHES "./blf_balancing_position_control/contact_wrenches.ini"]
[include GLOBAL_COP_EVALUATOR "./blf_balancing_position_control/global_cop_evaluator.ini"]
[include DATA_LOGGING "./blf_balancing_position_control/data_logging.ini"]
[include ADMITTANCE_CONTROL "./blf_balancing_position_control/admittance_control.ini"]

