
joints_list                             ("torso_pitch", "torso_roll", "torso_yaw",
                                         "l_shoulder_pitch", "l_shoulder_roll", "l_shoulder_yaw", "l_elbow",
                                         "r_shoulder_pitch", "r_shoulder_roll", "r_shoulder_yaw", "r_elbow",
                                         "l_hip_pitch", "l_hip_roll", "l_hip_yaw", "l_knee", "l_ankle_pitch", "l_ankle_roll",
                                         "r_hip_pitch", "r_hip_roll", "r_hip_yaw", "r_knee", "r_ankle_pitch", "r_ankle_roll")

; ; p_gains (these are the ones of the RL policy)
; kp_gains                               (125.0, 80.0, 20.0, 100.0, 60.0, 20.0,
;                                         125.0, 80.0, 20.0, 100.0, 60.0, 20.0)


; kp_gains (these are starting point for tuning) robot_logger_device_2025_05_27_10_44_43.mat
kp_gains                               (25.0, 16.0, 4.0, 20.0, 12.0, 4.0,
                                        25.0, 16.0, 4.0, 20.0, 12.0, 4.0)

; kp_gains (increasing hip_yaw, ankle_pitch and ankle_roll) robot_logger_device_2025_05_27_10_59_47.mat
kp_gains                               (25.0, 16.0, 10.0, 20.0, 20.0, 10.0,
                                        25.0, 16.0, 10.0, 20.0, 20.0, 10.0)

# setting fixed joints position in kindyn -> robot_logger_device_2025_05_27_11_22_11.mat

; the kd gains
kd_gains                               (5.0, 5.0, 5.0, 5.0, 1.0, 1.0,
                                        5.0, 5.0, 5.0, 5.0, 1.0, 1.0)

; the maximum torque
max_torque                             (100.0, 80.0, 20.0, 100.0, 30.0, 30.0,
                                        100.0, 80.0, 20.0, 100.0, 30.0, 30.0)

; the gear ratio
gear_ratio                             (-100.0, +160.0, -100.0, -100.0, -100.0, -160.0,
                                        +100.0, -160.0, +100.0, +100.0, +100.0, +160.0)

; the ktau
ktau                                   (0.111, 0.047, 0.047, 0.111, 0.111, 0.047,
                                        0.111, 0.047, 0.047, 0.111, 0.111, 0.047)
